[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：关闭
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

ruleset=自定义,https://raw.githubusercontent.com/i9412/lajitong/refs/heads/main/iii2.list
ruleset=TVB,https://raw.githubusercontent.com/i9412/lajitong/refs/heads/main/iii2_tvb.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=全球直连,[]GEOIP,CN
ruleset=漏网之鱼,[]FINAL

;节点选择：手动选择节点
custom_proxy_group=节点选择`select`[]DIRECT`.*

;国外媒体：手动选择
custom_proxy_group=国外媒体`select`[]节点选择`[]全球直连`.*

;电报信息：手动选择
custom_proxy_group=电报信息`select`[]节点选择`[]全球直连`.*

;微软服务：默认直连
custom_proxy_group=微软服务`select`[]全球直连`[]节点选择`.*

;苹果服务：默认代理
custom_proxy_group=苹果服务`select`[]节点选择`[]全球直连`.*

;全球直连：默认DIRECT
custom_proxy_group=全球直连`select`[]DIRECT`[]节点选择

;广告拦截
custom_proxy_group=全球拦截`select`[]REJECT`[]DIRECT

;应用净化
custom_proxy_group=应用净化`select`[]REJECT`[]DIRECT

;漏网之鱼：默认代理
custom_proxy_group=漏网之鱼`select`[]节点选择`[]全球直连`.*

;自定义规则：默认直连
custom_proxy_group=自定义`select`[]DIRECT`[]节点选择`[]全球直连`.*

;TVB规则：默认直连
custom_proxy_group=TVB`select`[]DIRECT`[]节点选择`[]全球直连`.*

;启用规则生成
enable_rule_generator=true

;覆盖原始规则
overwrite_original_rules=true